import request from 'supertest';
import { createApp } from '@/app';
import { Category, Kitchen, MenuItem, Notification, Room } from '@/models';
import { NOTIFICATION_TYPES, ROLES } from '@/constants';
import { createUserWithToken } from './helpers';

// Email mocked — assert it's *called* without hitting Brevo.
const sendNotificationEmail = jest.fn().mockResolvedValue(undefined);
jest.mock('@/services/email/brevo.service', () => ({
  emailService: {
    sendNotificationEmail: (...args: unknown[]) => sendNotificationEmail(...args),
    sendVerificationEmail: jest.fn().mockResolvedValue(undefined),
    sendPasswordResetEmail: jest.fn().mockResolvedValue(undefined),
    sendSecurityAlert: jest.fn().mockResolvedValue(undefined),
  },
}));

const app = createApp();

async function setupAndOrder() {
  const owner = await createUserWithToken(ROLES.KITCHEN_OWNER);
  const kitchen = await Kitchen.create({
    name: 'Notif Kitchen',
    slug: `nk-${Date.now()}-${Math.round(Math.random() * 1e6)}`,
    owner: owner.user._id,
    settings: { serviceChargePercent: 0, taxPercent: 0, acceptsCOD: true, acceptsRoomBilling: false },
  });
  owner.user.kitchen = kitchen._id;
  await owner.user.save();

  const room = await Room.create({
    roomNumber: `R${Math.round(Math.random() * 1e6)}`, floor: 1, kitchen: kitchen._id,
    qr: { token: `tok-${Math.round(Math.random() * 1e9)}`, isActive: true, version: 1 },
  });
  const category = await Category.create({ kitchen: kitchen._id, name: 'Mains', slug: 'mains' });
  const item = await MenuItem.create({
    kitchen: kitchen._id, category: category._id, name: 'Biryani', price: 250, taxPercent: 0, foodLabel: 'NON_VEG',
  });
  const customer = await createUserWithToken(ROLES.CUSTOMER);

  await request(app)
    .post('/api/v1/cart/items')
    .set('Authorization', customer.bearer)
    .send({ room: room._id.toString(), menuItem: item._id.toString(), quantity: 1 })
    .expect(201);
  const res = await request(app)
    .post('/api/v1/orders/checkout')
    .set('Authorization', customer.bearer)
    .send({ kitchen: kitchen._id.toString(), paymentMethod: 'COD' })
    .expect(201);

  return { owner, kitchen, customer, orderId: res.body.data.order._id as string };
}

describe('Notifications — generated by order events', () => {
  beforeEach(() => {
    sendNotificationEmail.mockClear();
  });

  it('notifies the customer (received) and the kitchen (new order) on checkout', async () => {
    const { owner, customer } = await setupAndOrder();
    
    // Wait for the async fire-and-forget notification email to finish sending.
    await new Promise((resolve) => setTimeout(resolve, 100));

    const custNotifs = await Notification.find({ recipient: customer.user._id });
    expect(custNotifs.map((n) => n.type)).toContain(NOTIFICATION_TYPES.ORDER_RECEIVED);

    const ownerNotifs = await Notification.find({ recipient: owner.user._id });
    expect(ownerNotifs.map((n) => n.type)).toContain(NOTIFICATION_TYPES.KITCHEN_NEW_ORDER);

    // ORDER_RECEIVED requested the EMAIL channel.
    expect(sendNotificationEmail).toHaveBeenCalled();
  });

  it('notifies the customer as the order status advances', async () => {
    const { owner, customer, orderId } = await setupAndOrder();
    await request(app)
      .patch(`/api/v1/orders/${orderId}/status`)
      .set('Authorization', owner.bearer)
      .send({ status: 'ACCEPTED' })
      .expect(200);

    const accepted = await Notification.findOne({
      recipient: customer.user._id,
      type: NOTIFICATION_TYPES.ORDER_ACCEPTED,
    });
    expect(accepted).toBeTruthy();
  });

  it('notifies both parties on cancellation', async () => {
    const { owner, customer, orderId } = await setupAndOrder();
    await request(app)
      .post(`/api/v1/orders/${orderId}/cancel`)
      .set('Authorization', owner.bearer)
      .send({ reason: 'Item unavailable' })
      .expect(200);

    expect(
      await Notification.findOne({ recipient: customer.user._id, type: NOTIFICATION_TYPES.ORDER_CANCELLED }),
    ).toBeTruthy();
    expect(
      await Notification.findOne({ recipient: owner.user._id, type: NOTIFICATION_TYPES.KITCHEN_CANCELLATION }),
    ).toBeTruthy();
  });
});

describe('Notifications — feed API', () => {
  it('lists notifications with an unread count and marks them read', async () => {
    const { customer } = await setupAndOrder();

    const listRes = await request(app)
      .get('/api/v1/notifications')
      .set('Authorization', customer.bearer)
      .expect(200);
    expect(listRes.body.data.unreadCount).toBeGreaterThanOrEqual(1);
    const first = listRes.body.data.notifications[0];

    await request(app)
      .patch(`/api/v1/notifications/${first._id}/read`)
      .set('Authorization', customer.bearer)
      .expect(200);

    const countRes = await request(app)
      .get('/api/v1/notifications/unread-count')
      .set('Authorization', customer.bearer)
      .expect(200);
    expect(countRes.body.data.unreadCount).toBe(listRes.body.data.unreadCount - 1);
  });

  it('marks all as read', async () => {
    const { customer } = await setupAndOrder();
    await request(app).patch('/api/v1/notifications/read-all').set('Authorization', customer.bearer).expect(200);
    const countRes = await request(app)
      .get('/api/v1/notifications/unread-count')
      .set('Authorization', customer.bearer)
      .expect(200);
    expect(countRes.body.data.unreadCount).toBe(0);
  });

  it('only exposes the recipient’s own notifications', async () => {
    const { customer } = await setupAndOrder();
    const stranger = await createUserWithToken(ROLES.CUSTOMER);
    const res = await request(app).get('/api/v1/notifications').set('Authorization', stranger.bearer).expect(200);
    expect(res.body.data.notifications).toHaveLength(0);
    // ensure the other customer's notifications exist but aren't leaked
    expect(await Notification.countDocuments({ recipient: customer.user._id })).toBeGreaterThan(0);
  });

  it('dispatches SMS to user or guest successfully', async () => {
    const { notify } = await import('@/services/notification.service');
    const customer = await createUserWithToken(ROLES.CUSTOMER);
    customer.user.phone = '+919999988888';
    await customer.user.save();

    await notify({
      recipient: customer.user._id.toString(),
      type: NOTIFICATION_TYPES.ORDER_RECEIVED,
      title: 'SMS Test',
      message: 'Hello SMS user',
      channels: ['SMS'],
    });
  });
});
