import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';

export type Cell = string | number | null | undefined;
export interface Table {
  title: string;
  headers: string[];
  rows: Cell[][];
}

function escapeCsv(value: Cell): string {
  const s = value == null ? '' : String(value);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

/** Render a table as CSV text. */
export function toCsv(table: Table): string {
  const lines = [table.headers.map(escapeCsv).join(',')];
  for (const row of table.rows) lines.push(row.map(escapeCsv).join(','));
  return lines.join('\n');
}

/** Render a table as an .xlsx workbook buffer. */
export async function toExcel(table: Table): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'KDS';
  const sheet = wb.addWorksheet(table.title.slice(0, 31) || 'Report');
  sheet.addRow(table.headers);
  sheet.getRow(1).font = { bold: true };
  for (const row of table.rows) sheet.addRow(row);
  sheet.columns.forEach((col) => {
    let max = 10;
    col.eachCell?.({ includeEmpty: true }, (cell) => {
      max = Math.max(max, String(cell.value ?? '').length + 2);
    });
    col.width = Math.min(max, 40);
  });
  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}

/** Render a table as a simple, paginated PDF buffer. */
export function toPdf(table: Table): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).text(table.title, { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor('#666').text(`Generated by KDS`, { align: 'right' });
    doc.moveDown();

    const colWidth = (doc.page.width - 80) / table.headers.length;
    const drawRow = (cells: Cell[], bold = false) => {
      const y = doc.y;
      doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9).fillColor('#000');
      cells.forEach((cell, i) => {
        doc.text(String(cell ?? ''), 40 + i * colWidth, y, { width: colWidth - 4, ellipsis: true });
      });
      doc.moveDown(0.4);
      if (doc.y > doc.page.height - 60) doc.addPage();
    };

    drawRow(table.headers, true);
    doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).strokeColor('#ccc').stroke();
    doc.moveDown(0.2);
    for (const row of table.rows) drawRow(row);

    doc.end();
  });
}

export const EXPORT_MIME = {
  csv: 'text/csv',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pdf: 'application/pdf',
} as const;
